name: Beta CI/CD Build

on:
  push:
    branches: [ "develop" ] # Срабатывает только для develop

jobs:
  build-beta:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Beta APK
        run: ./gradlew clean assembleDebug

      # Сохраняем APK как артефакт (он будет доступен для скачивания во вкладке Actions)
      - name: Upload Beta APK
        uses: actions/upload-artifact@v4
        with:
          name: cheese-roulette-beta
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7 # Артефакт хранится 7 дней, чтобы не занимать место